export const HERB_CATEGORIES = [
  { name: "Adaptogen", slug: "adaptogen", icon: "Shield", description: "Herbs that help the body resist stressors" },
  { name: "Anti-inflammatory", slug: "anti-inflammatory", icon: "Flame", description: "Herbs that reduce inflammation" },
  { name: "Antimicrobial", slug: "antimicrobial", icon: "Bug", description: "Herbs with antimicrobial properties" },
  { name: "Antioxidant", slug: "antioxidant", icon: "Sparkles", description: "Herbs rich in antioxidants" },
  { name: "Cardiovascular", slug: "cardiovascular", icon: "Heart", description: "Herbs supporting heart and circulation" },
  { name: "Digestive", slug: "digestive", icon: "Apple", description: "Herbs aiding digestion and gut health" },
  { name: "Immune Support", slug: "immune", icon: "ShieldCheck", description: "Herbs that boost immune function" },
  { name: "Nervous System", slug: "nervous-system", icon: "Brain", description: "Herbs supporting brain and nerves" },
  { name: "Respiratory", slug: "respiratory", icon: "Wind", description: "Herbs for lung and respiratory health" },
  { name: "Skin Health", slug: "skin", icon: "Droplets", description: "Herbs for skin conditions and care" },
  { name: "Urinary", slug: "urinary", icon: "Droplet", description: "Herbs supporting urinary tract health" },
  { name: "Women's Health", slug: "womens-health", icon: "Baby", description: "Herbs for women's health concerns" },
  { name: "Men's Health", slug: "mens-health", icon: "Dumbbell", description: "Herbs for men's health concerns" },
  { name: "Pain Relief", slug: "pain-relief", icon: "Zap", description: "Natural analgesic and pain-relieving herbs" },
  { name: "Sleep & Relaxation", slug: "sleep", icon: "Moon", description: "Herbs promoting sleep and relaxation" },
  { name: "Other", slug: "other", icon: "Leaf", description: "Other medicinal herbs" },
] as const;
